### ISSUE TITLE
version:absorb not reading latest commit hash

### ISSUE THREAD

**Issue by nabeelio** [antonioribeiro/version#30]
When running `version:refresh` or `version:absorb`, it should update `build.number` in the YAML file, but I can't seem to get it to update. I am on the master branch. I delete the `.git` directory in the distribution tarball since it ends up being about 50mb, without it, the tar is about 8mb. But that's an aside.

```bash
$ git log <snipped>

commit d63f0ee2f8f1c9078621a83da8692fe3d56df3ae (HEAD -> master, origin/master, origin/HEAD)

$ php artisan version:refresh

Version was refreshed.
phpvms version 7.0.0 (build 451e9e)

$ php artisan version:absorb
In Git.php line 46:

  No git tags not found in this repository
```
`451e9e` is from Dec 15th (crazy I didn't notice till now...). It was working when just running this:

```bash
php artisan version:show --format compact --suppress-app-name
```
But, not it's not updating at all. I'm not sure what's changed. My config is this:

```yaml
version_source: config # "config", "git-local" or "git-remote"
current:
  major: 7
  minor: 0
  patch: 0
  git_absorb: git-local
  format: "{$major}.{$minor}.{$patch}"
build:
  mode: number
  number: 451e9e
  git_absorb: git-local
git:
  git-local: "git rev-parse --verify HEAD"
  git-remote: "git ls-remote {$repository}"
  branch: "refs/heads/master"
  repository: "{{ env('VERSION_GIT_REMOTE_REPOSITORY') }}"
  version:
    git-local: "git describe"
    git-remote: "git ls-remote {$repository} | grep tags/ | grep -v {} | cut -d \/ -f 3 | sort --version-sort | tail -1"
    matcher: "/[V|v]*[ersion]*\\s*\\.*(\\d+)\\.(\\d+)\\.(\\d+)\\.*(\\w*)/"
format:
  major: "{$major}"
  minor: "{$minor}"
  patch: "{$patch}"
  build: "{$build}"
  version: "{$major}.{$minor}.{$patch} (build {$build})"
  full: "version {{'format.version'}}"
  compact: "v{$major}.{$minor}.{$patch}-{$build}"
  ## add as many formats as you need !!!!
```
