### ISSUE TITLE
(suggest) Lead zero & v max

### ISSUE THREAD

**Issue by Deefaze** [antonioribeiro/version#39]
Hi, First thank for this cool code !

But, I am a little bit disappointed :

**1** - no lead zero in Patch and Build (number incrementable mode), in natural order or, just for styling, lead zero in this two field is better than no-lz. 
Natural order != number order, the annoying problem :
- 1.1.1 
- 1.10.1 <- not the good place 
- 1.3.1

With LZ :
- 1.01.01
- 1.03.01
- 1.10.01 <- good place

This can be easy to fix with a function like sprintf %.2d %.3d etc.
Yaml can be modified like this :
```yaml
field: # can be major | minor | patch | build
  val: 1 # value of field
  lead: 0 # format descriptor précision : n<2 or not set or null =  %d  | n>1  = %.nd (max 4)
  inc: 1 # val increment
```

**2** -  v max & auto inc superior field :
version part is not human readable above 99 (on multiple field) or 999 (on one field)
v16.1248.3469 ... not cool
hex format ? :
v16.4E0.D8D ... not really cool ... 

v26.76.084 ... sound little better, no ?

Well, UP to BIG major.  By default, can be :
Patch max 0..255
Minor max 0..255
Like, RAD Studio (Delphi), version controller. This made bigger major number. Only build can be huge number or hex format (like the current on git-local/remote)

Extend yaml :
```yaml
field: # can be major | minor | patch | build
  val: 1 # value of field
  lead: 0 # format descriptor précision : n<2 or not set or null =  %d  | n>1  = %.nd (max 4)
  inc: 1 # val increment
  max: 255 # if at the next inc, val = 256, val return to 0, next field is incremented. 
  # major and build field ignore max.
```

Logic, (not tested), from scratch :
```php
class TVersionBuilderField
{
  protected $_val; // field value
  protected $_lead; // lead zero control
  protected $_inc; // increment val
  protected $_max; // max value of val
  protected $_ignore; // ignore max value
  protected $_reset; // val < 0 or val > max, ctrl

  function __construct($aVal=0, $aLead=0, $aInc=1, $aMax=255, $aIgnore=false)
  {
    $this->_val    = $aVal;
    $this->_lead   = $aLead==0 ? '%d':'%.'.$aLead.'d'; // select the good descriptor
    $this->_inc    = $aInc;
    $this->_max    = $aMax;
    $this->_ignore = $aIgnore || $aMax == 0; // force ignore from null max
    $this->_reset   = false;
  }

  // return true if val has exceeded interval 0..max on last inc/dec call, else false.
  public function reset()
  {
    return $this->_reset;
  }

  // return raw value of val
  public function toInt()
  {
    return $this->_val;
  }

  // return val at hex format (without precision) 
  public function toHex()
  {
    return sprintf('%x', $this->_val);
  }

  // return val at string format (with or without precision : n, 0n, 00n ...)
  public function toStr()
  {
    return sprintf($this->_lead, $this->_val);
  }

  // controlled val incrementation
  function inc()
  {
    $this->_reset = false;
    $this->_val += $this->_inc;
    if( !$this->ignore )
    {
      $this->_reset = $this->_val > $this->_max;
      if( $this->_reset )
      {
        $this->_val = 0;
      }
    }
    return $this;
  }

  // controlled val decrementation
  function dec()
  {
    $this->_reset = false;
    $this->_val -= $this->_inc;
    $this->_reset = $this->_val < 0;
    if( $this->_reset )
    {
      $this->_val = !$this->ignore ? ($this->_max - $this->_val) : 0;
    }
    return $this;
  }
}

// main version class
class TVersionBuilder
{
  function __construct($aMajor, $aMinor, $aPatch)
  {
    $this->major = new TVersionBuilderField($aMajor, 0, 1, 0,  true);
    $this->minor = new TVersionBuilderField($aMinor, 2, 1, 99, false);
    $this->patch = new TVersionBuilderField($aPatch, 2, 1, 99, false);
  }

  // main inc caller, with auto fields inc.
  function inc()
  {
    if( $this->patch->inc()->reset() )
    {
      if( $this->minor->inc()->reset() )
      {
        $this->major->inc();
      }
    }
    return $this;
  }

  // main dec caller, with auto fields dec and no under-zero ctrl
  function dec()
  {
    if( $this->patch->toInt() > 0)
    {
      if( $this->patch->dec()->reset() )
      {
        if( $this->minor->toInt() > 0 )
        {
          if( $this->minor->dec()->reset() )
          {
            if( $this->major->toInt() > 0 ) $this->major->dec();
          }
        }
      }
    }
    return $this;
  }

  // return full version raw string like 1.1.1 or 1.02.03 or 1.2.034 ...
  function toStr()
  {
    return sprintf('%s.%s.%s', $this->major->toStr(), $this->minor->toStr(), $this->patch->toStr());
  }
}
```

What do you think ?
