### ISSUE TITLE
No git tags found in this repository

### ISSUE THREAD

**Issue by camaech** [antonioribeiro/version#48]
I can't ever get this to work on my staging server. Working fine on local using git-local.

> @php artisan version:refresh
> In Git.php line 47:
>                                         
>   No git tags found in this repository  
>                                         
> Script @php artisan version:refresh handling the post-autoload-dump event returned with error code 1
> 

Here is my version.yml file
![version_yml_-_roastar_com_-____documents_laravel_homestead_sites_roastar_com_](https://user-images.githubusercontent.com/977957/40752798-bccb8978-6436-11e8-8f9b-995c34fc7d6f.png)

**Comment by allw1994** [comment]
Exact same issue but above solution did not solve it for me, using version format of either v0.1 or v0.1.0 etc

**Comment by ole1986** [comment]
When you are using git version 2.20.0 there might be an issue with git itself fetching the tags due to some internal errors.

Updating to version 2.20.1 fixed it for me

**Comment by antonioribeiro** [comment]
Yeah, it's probably impossible to support all git versions, but if the git commands we have are not able to get version history for your application, don't be afraid to tweak the config, here are the ones it uses to get version info for local and remote repository, and the regex version matcher:

``` yaml
version:
  git-local: "git describe"
  git-remote: "git ls-remote {$repository} | grep tags/ | grep -v {} | cut -d \/ -f 3 | sort --version-sort | tail -1"
  matcher: "/[V|v]*[ersion]*\\s*\\.*(\\d+)\\.(\\d+)\\.(\\d+)\\.*(\\w*)/"
```
