### ISSUE TITLE
git-local build [commit] hash is not updating

### ISSUE THREAD

**Issue by allw1994** [antonioribeiro/version#52]
My debug environment has no issues with versioning (whatsoever) but my staging environment will not show the latest commit hash and will not use tags. I am happy to forego using tags, but the build hash is critical!

The build number is not the one defaulted in the config, but an old commit?

Any ideas what is wrong?

````
version_source: config
blade_directive: version
current:
    major: 0
    minor: 1
    patch: 10
    format: '{$major}.{$minor}.{$patch}'
    git_absorb: false
cache:
    enabled: true
    key: pragmarx-version
    time: 525600
build:
    mode: git-local
    number: 701031
    length: 6
    increment_by: 1
    git_absorb: false
git:
    git-local: 'git rev-parse --verify HEAD'
    git-remote: 'git ls-remote {$repository}'
    branch: refs/heads/master
    repository: 'hidden'
    version: { git-local: 'git describe', git-remote: 'git ls-remote {$repository} | grep tags/ | grep -v {} | cut -d / -f 3 | sort --version-sort | tail -1', matcher: '/[V|v]*[ersion]*\s*\.*(\d+)\.(\d+)\.(\d+)\.*(\w*)/' }
format:
    major: '{$major}'
    minor: '{$minor}'
    patch: '{$patch}'
    build: '{$build}'
    version: '{$major}.{$minor}.{$patch} (build {$build})'
    full: 'version {$major}.{$minor}.{$patch} (build {$build})'
    compact: 'v{$major}.{$minor}.{$patch}-{$build}'
````
